opm-server:
    host: http://www.linkstream.org

opm-client:
    clientid: 1
    max-parallel-requests: 2

phantom:
    executable: /app1/ela/var/www/app/test.local/ocm/client/vendor/phantomjs/